name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm i -g yarn
      - run: yarn config set checksumBehavior ignore
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: |
            ./.yarn/cache
            ./.yarn/unplugged
          key: ${{ runner.os }}-yarn2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn2-
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: diff outputs
          path: src/**/__diff_output__/*.png
      - name: Prepare Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          mkdir -p public/build
          cp README.md public/README.md
          cp -r examples public/
          cp build/venn.js public/build/
      - name: Deploy
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          enable_jekyll: true
